---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}

  library(tidyverse)
  library(p8105.datasets)
  library(plotly)
  library(flexdashboard)
  library(dplyr)
  library(rnoaa)
  library(ggplot2)

```

```{r}
    
  # Get a list of all NY station IDs
  stations <- ghcnd_stations() %>% drop_na()
  nystationids <- stations %>% filter(state == "NY") %>% distinct(id)
  
  # Pull the desired weather data for all of these stations
  nydat <- meteo_pull_monitors(nystationids$id, 
                               date_min = "1981-01-01", 
                               date_max = "2010-12-31", 
                               var = c("PRCP", "SNOW", "SNWD", "TMAX", "TMIN"))
  
  # Save the resulting data
  save(nystationids, nydat, file = "nynoaadat.RData")


```

```{r}

  nydat = nydat %>% drop_na()
  nystationids = nystationids %>% drop_na()
  stations = stations %>% drop_na()

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r Scatterplot}
  
  # Scatterplot of station locations with color representing elevation
  ggplot(stations, aes(x = longitude, y = latitude, color = elevation)) +
    geom_point(alpha = 0.7, size = 0.35) +
    scale_color_viridis_c(option = "C") +  # Use a color gradient suitable for elevation
    labs(title = "Station Locations by Elevation",
         x = "Longitude",
         y = "Latitude",
         color = "Elevation (m)") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))


```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r Boxplot, fig.width=15, fig.height=12}

  # Boxplot of elevation by element
  ggplot(stations, aes(x = element, y = elevation)) +
    geom_boxplot(fill = "lightgreen", outlier.size = 0.5, outlier.alpha = 0.5) +
    labs(title = "Elevation Distribution by Element",
         x = "Element",
         y = "Elevation (m)") +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(angle = 45, hjust = 1, size = 5) 
    )

```

### Chart C

```{r}

  # Summarize data to get the number of stations recording each element by year
  yearly_counts <- stations %>%
                    group_by(first_year, element) %>%
                    summarise(station_count = n()) %>%
                    ungroup()

# Line plot of station counts by year for each element with no legend
  ggplot(yearly_counts, aes(x = first_year, y = station_count, color = element, size=0.5)) +
    geom_line(size = 0.4) +
    labs(title = "Number of Stations Recording Each Element Over Time",
         x = "Year",
         y = "Number of Stations") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          legend.position = "none")


```

