---
title: "Plotly Examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r Load Packages, include=FALSE}
  library(tidyverse)
  library(p8105.datasets)
  library(plotly)
  library(flexdashboard)
```

```{r, include=FALSE}
  data("nyc_airbnb")
  nyc_airbnb = nyc_airbnb %>%  
               mutate(rating = review_scores_location / 2) %>% 
               select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
               filter(!is.na(rating), neighbourhood_group == "Manhattan", room_type == "Entire home/apt", price %in% 100:500)
```

### Scatterplot
```{r, message=FALSE, warning=FALSE, echo=FALSE}
  nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers", color = ~price, text = ~text_label, alpha = 0.5, marker = list(size = 2.5))
```

### Boxplot
```{r, message=FALSE, warning=FALSE, echo=FALSE}
  nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis", marker = list(size = 2.5))
```

### Barplot
```{r, message=FALSE, warning=FALSE, echo=FALSE}
  nyc_airbnb %>%  
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

### ggplotly
```{r, message=FALSE, warning=FALSE, echo=FALSE}
  ggscatter = nyc_airbnb %>% 
              ggplot(aes(x=lat, y=long, color=price)) + geom_point(size=.35)
  ggplotly(ggscatter)
```



