<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>R project sample</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="within_page.html">Secret Number</a>
</li>
<li>
  <a href="dashboard.html">Dashboard</a>
</li>
<li>
  <a href="mailto:&lt;zhangenju1999121@gmail.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/Xs-761/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">R project sample</h1>

</div>


<pre class="r"><code># Load Necessary Packages
  library(ggplot2)
  library(tidyverse)
  library(dplyr)
  library(tidyr)
  library(rvest)

# Preliminary Loading of All Datasets
  NYC_Rental_Price = read.csv(&quot;./datasets/NYC Rental.csv&quot;)
  US_Housing_Price = read.csv(&quot;./datasets/US Housing 2023.csv&quot;)
  NYC_Zipcode      = rvest::read_html(&quot;https://p8105.com/data/zip_codes.html&quot;) %&gt;% html_table(fill = TRUE) %&gt;% mutate(.=.[[1]])</code></pre>
<ul>
<li>Raw Data
<ul>
<li><code>NYC_Zipcode</code>
<ul>
<li>Dimension: 322 x 8<br />
</li>
<li>Description: The <code>NYC_Zipcode</code> Dataset contains data of
Zipcode-Location associations within entire NYC.<br />
</li>
</ul></li>
<li><code>NYC_Rental_Price</code>
<ul>
<li>Dimension: 149 x 125<br />
</li>
<li>Description: The <code>NYC_Rental_Price</code> Dataset contains
rental price data within NYC from year 2015 to 2018.<br />
</li>
</ul></li>
<li><code>US_Housing_Price</code>
<ul>
<li>Dimension: 26338 x 21<br />
</li>
<li>Description: The <code>US_Housing_Price</code> Dataset contains
housing price data within entire U.S. in year 2023.<br />
</li>
</ul></li>
</ul></li>
<li>Goal
<ul>
<li>Clean, Analyze, Interpret, Visualize using NYC_Rental and US_Housing
datasets</li>
</ul></li>
</ul>
<pre class="r"><code># Raw-Data -&gt; Pivot Longer -&gt; Filter out Redundant Columns
  NYC_Rental_Price = NYC_Rental_Price %&gt;% 
                     select(RegionName, CountyName, starts_with(&quot;X&quot;)) %&gt;% 
                     janitor::clean_names() %&gt;% 
                     rename(&quot;zipcode&quot;=&quot;region_name&quot;, &quot;county&quot;=&quot;county_name&quot;) %&gt;% 
                     mutate(county=gsub(&quot; County&quot;,&quot;&quot;,county)) %&gt;% 
                     mutate(across(where(is.numeric), round, 2)) %&gt;% 
                     pivot_longer(cols=starts_with(&quot;x&quot;), names_to=&quot;date&quot;, values_to=&quot;rental_price&quot;) %&gt;% 
                     mutate(date=gsub(&quot;x&quot;,&quot;&quot;,date)) %&gt;% 
                     mutate(date=gsub(&quot;_&quot;,&quot;/&quot;,date))
  
  NYC_Zipcode = NYC_Zipcode %&gt;% 
                janitor::clean_names() %&gt;% 
                select(county, zip_code, neighborhood) %&gt;% 
                rename(&quot;zipcode&quot;=&quot;zip_code&quot;) %&gt;% 
                mutate(borough=recode(county, &quot;Kings&quot;=&quot;Brooklyn&quot;, &quot;New York&quot;=&quot;Manhattan&quot;, &quot;Richmond&quot;=&quot;Staten Island&quot;)) %&gt;% 
                relocate(zipcode, county, borough)

  US_Housing_Price = US_Housing_Price %&gt;% 
                     janitor::clean_names() %&gt;% 
                     select(city, region_name, state, starts_with(&quot;x&quot;)) %&gt;% 
                     rename(&quot;zipcode&quot;=&quot;region_name&quot;) %&gt;% 
                     arrange(zipcode) %&gt;%
                     pivot_longer(cols=starts_with(&quot;x&quot;), names_to=&quot;date&quot;, values_to=&quot;housing_price&quot;) %&gt;% 
                     mutate(date=gsub(&quot;x&quot;,&quot;&quot;,date)) %&gt;% 
                     mutate(date=gsub(&quot;_&quot;,&quot;/&quot;,date)) %&gt;% 
                     relocate(zipcode)

# Rectify incorrect zipcodes
  NYC_Zipcode %&gt;% filter(zipcode==11201 | zipcode==10463) %&gt;% select(zipcode, county, borough) # correct data should be: 11201--Kings--Brooklyn &amp; 10463--Bronx--Bronx</code></pre>
<pre><code>## # A tibble: 4 × 3
##   zipcode county   borough  
##     &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;    
## 1   10463 Bronx    Bronx    
## 2   11201 Kings    Brooklyn 
## 3   10463 New York Manhattan
## 4   11201 New York Manhattan</code></pre>
<pre class="r"><code>  NYC_Zipcode = NYC_Zipcode %&gt;% filter(!(zipcode==11201 &amp; county==&quot;New York&quot;)) %&gt;% filter(!(zipcode==10463 &amp; county==&quot;New York&quot;)) # select all correct zipcodes

# Create Merged Dataset
  Merged = left_join(x=NYC_Zipcode, y=NYC_Rental_Price, by=&quot;zipcode&quot;) %&gt;%
           rename(&quot;county&quot;=&quot;county.x&quot;) %&gt;% 
           relocate(zipcode, county, borough, neighborhood) %&gt;% 
           select(-county.y)</code></pre>
<ul>
<li>When merging datasets, warning message appears<br />
</li>
<li>Upon checking, zipcode all unique in <code>NYC_Rental_Price</code>
and <code>NYC_Housing Price</code>, but contain duplicate values 10463
and 11201 in <code>NYC_Zipcode</code>. Remove incorrect records.<br />
</li>
<li>Upon removal of incorrect observations, the join was performed
successfully with the resulting <code>Merged</code> dataset.</li>
<li>Description on the <code>Merged</code> dataset:
<ul>
<li>Dimension: 17455 x 6.<br />
</li>
<li>Unique Zipcodes Included: 320<br />
</li>
<li>Unique Neighborhood Include: 43<br />
</li>
</ul></li>
<li>Data Manipulation
<ul>
<li>In both <code>NYC_Rental_Price</code> and
<code>US_Housing_Price</code> datasets, changed <code>RegionName</code>
to <code>zipcode</code>.<br />
</li>
<li>Converted <code>NYC_Rental_Price</code> and
<code>NYC_Rental_Price</code> to a longer format with all date variables
listed under column <code>date</code> and values listed under column
<code>rental_price</code> and <code>housing_price</code>,
respectively.<br />
</li>
<li>Redundant Column Names
<ul>
<li>In <code>NYC_Zipcode</code> dataset, I kept only the
<code>zipcode</code>, <code>county</code>, <code>borough</code>,
<code>neighborhood</code> columns.<br />
</li>
<li>In <code>NYC_Rental_Price</code> dataset, I kept only the
<code>zipcode</code>, <code>county</code>, <code>date</code>,
<code>rental_price</code> columns.<br />
</li>
<li>In <code>US_Housing_Price</code> dataset, I kept only the
<code>zipcode</code>, <code>city</code>, <code>state</code>,
<code>housing_price</code> columns.</li>
</ul></li>
</ul></li>
</ul>
<pre class="r"><code># Table 1 --- average rental price in each borough and year
  Table1 = Merged %&gt;% 
           separate(date, into=c(&quot;year&quot;,&quot;month&quot;,&quot;day&quot;), sep=&quot;/&quot;) %&gt;% 
           group_by(borough, year) %&gt;% 
           summarise(mean_rental_price=mean(rental_price, na.rm=TRUE)) %&gt;% 
           pivot_wider(names_from=borough, values_from=mean_rental_price) %&gt;% 
           filter(!is.na(year))

# Table 2 --- comparing average rental prices from 2020 to 2021
  Table2 = Merged %&gt;% 
           separate(date, into=c(&quot;year&quot;,&quot;month&quot;,&quot;day&quot;), sep=&quot;/&quot;) %&gt;% 
           filter( (year==&quot;2020&quot;|year==&quot;2021&quot;) &amp; month==c(&quot;1&quot;) ) %&gt;% 
           group_by(year) %&gt;% 
           select(zipcode, year, rental_price) %&gt;% 
           rename(&quot;January_of_Year&quot;=&quot;year&quot;) %&gt;% 
           pivot_wider(names_from=January_of_Year, values_from=rental_price) %&gt;% 
           rename(&quot;Jan.2020&quot;=&quot;2020&quot;, &quot;Jan.2021&quot;=&quot;2021&quot;) %&gt;% 
           arrange(zipcode) %&gt;% 
           mutate(absolute_change = Jan.2021-Jan.2020, relative_percentage_change = (Jan.2021 - Jan.2020) / Jan.2020 * 100) %&gt;% 
           mutate(across(where(is.numeric),round, 2))

# Table 3 --- for each borough, select neighborhood with largest drop in rental price from Jan.2020 to Jan.2021 
  Table3 =  Merged %&gt;% 
            separate(date, into=c(&quot;year&quot;,&quot;month&quot;,&quot;day&quot;), sep=&quot;/&quot;) %&gt;% 
            filter((year %in% c(&quot;2020&quot;, &quot;2021&quot;)) &amp; (month==&quot;1&quot;)) %&gt;%
            pivot_wider(names_from = year, values_from = rental_price, names_prefix = &quot;Jan.&quot;) %&gt;%
            mutate(drop = Jan.2020 - Jan.2021) %&gt;% 
            filter(!is.na(drop)) %&gt;% 
            group_by(borough) %&gt;%
            arrange(borough, desc(drop)) %&gt;%
            slice(1) %&gt;%
            select(-zipcode, -month, -day, -county)

# Table 4 --- average house price within each ZIP code over 2023
  Table4 = US_Housing_Price %&gt;% 
           separate(date, into=c(&quot;year&quot;,&quot;month&quot;,&quot;day&quot;), sep=&quot;/&quot;) %&gt;% 
           group_by(zipcode, year) %&gt;% 
           summarise(mean_housing_price=mean(housing_price)) %&gt;% 
           mutate(year=as.numeric(year), mean_housing_price=round(mean_housing_price,digits=0)) %&gt;% 
           select(-year)</code></pre>
<ul>
<li>Month Discrepancy
<ul>
<li>Some months do not have meaningful research values for
collection.</li>
<li>Decided not to include some Months as the rental prices data are too
incomplete within this period.<br />
</li>
</ul></li>
<li>Zipcode Discrepancy
<ul>
<li><code>NYC_Rental_Price</code> dataset has 149 but
<code>NYC_Zipcode</code> dataset has 320 zipcodes is because it is not
necessary to include rental price data for every single zipcode within
NYC.<br />
</li>
</ul></li>
<li>Table1:</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="left">year</th>
<th align="right">Bronx</th>
<th align="right">Brooklyn</th>
<th align="right">Manhattan</th>
<th align="right">Queens</th>
<th align="right">Staten Island</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2015</td>
<td align="right">1759.596</td>
<td align="right">2492.928</td>
<td align="right">3022.042</td>
<td align="right">2214.707</td>
<td align="right">NaN</td>
</tr>
<tr class="even">
<td align="left">2016</td>
<td align="right">1520.195</td>
<td align="right">2520.357</td>
<td align="right">3038.818</td>
<td align="right">2271.955</td>
<td align="right">NaN</td>
</tr>
<tr class="odd">
<td align="left">2017</td>
<td align="right">1543.599</td>
<td align="right">2545.828</td>
<td align="right">3133.848</td>
<td align="right">2263.303</td>
<td align="right">NaN</td>
</tr>
<tr class="even">
<td align="left">2018</td>
<td align="right">1639.429</td>
<td align="right">2547.291</td>
<td align="right">3183.703</td>
<td align="right">2291.918</td>
<td align="right">NaN</td>
</tr>
<tr class="odd">
<td align="left">2019</td>
<td align="right">1705.589</td>
<td align="right">2630.503</td>
<td align="right">3310.409</td>
<td align="right">2387.816</td>
<td align="right">NaN</td>
</tr>
<tr class="even">
<td align="left">2020</td>
<td align="right">1811.443</td>
<td align="right">2555.051</td>
<td align="right">3106.518</td>
<td align="right">2315.632</td>
<td align="right">1977.608</td>
</tr>
<tr class="odd">
<td align="left">2021</td>
<td align="right">1857.776</td>
<td align="right">2549.890</td>
<td align="right">3136.632</td>
<td align="right">2210.787</td>
<td align="right">2045.430</td>
</tr>
<tr class="even">
<td align="left">2022</td>
<td align="right">2054.267</td>
<td align="right">2868.199</td>
<td align="right">3778.375</td>
<td align="right">2406.038</td>
<td align="right">2147.436</td>
</tr>
<tr class="odd">
<td align="left">2023</td>
<td align="right">2285.459</td>
<td align="right">3015.183</td>
<td align="right">3932.610</td>
<td align="right">2561.615</td>
<td align="right">2332.934</td>
</tr>
<tr class="even">
<td align="left">2024</td>
<td align="right">2496.896</td>
<td align="right">3125.657</td>
<td align="right">4078.440</td>
<td align="right">2693.584</td>
<td align="right">2536.443</td>
</tr>
</tbody>
</table>
<ul>
<li>Remarks on Table1
<ul>
<li>Across most boroughs, rental prices has a general increasing trend
over year 2015-2024.<br />
</li>
<li>Manhattan has the highest rental prices among all boroughs, with
prices rising from 3022.04 in 2015 to 4078.44 in 2024.<br />
</li>
<li>Staten Island data missing from 2015 to 2019.</li>
<li>Price variation significant: Manhattan highest rental prices while
the Staten Island lowest prices(for available years).<br />
</li>
</ul></li>
<li>The following is a selection of Table2 giving a comparison of rental
prices in Jan.2021 to rental prices in Jan.2020:</li>
</ul>
<table>
<colgroup>
<col width="11%" />
<col width="13%" />
<col width="13%" />
<col width="23%" />
<col width="39%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">zipcode</th>
<th align="right">Jan.2020</th>
<th align="right">Jan.2021</th>
<th align="right">absolute_change</th>
<th align="right">relative_percentage_change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">10001</td>
<td align="right">4108.10</td>
<td align="right">3397.65</td>
<td align="right">-710.45</td>
<td align="right">-17.29</td>
</tr>
<tr class="even">
<td align="right">10002</td>
<td align="right">3645.42</td>
<td align="right">2935.11</td>
<td align="right">-710.31</td>
<td align="right">-19.48</td>
</tr>
<tr class="odd">
<td align="right">10003</td>
<td align="right">3569.78</td>
<td align="right">2897.24</td>
<td align="right">-672.54</td>
<td align="right">-18.84</td>
</tr>
<tr class="even">
<td align="right">10004</td>
<td align="right">3149.66</td>
<td align="right">2443.70</td>
<td align="right">-705.96</td>
<td align="right">-22.41</td>
</tr>
<tr class="odd">
<td align="right">10005</td>
<td align="right">3407.59</td>
<td align="right">2917.90</td>
<td align="right">-489.69</td>
<td align="right">-14.37</td>
</tr>
<tr class="even">
<td align="right">10006</td>
<td align="right">NA</td>
<td align="right">2956.05</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="right">10007</td>
<td align="right">6334.21</td>
<td align="right">5421.61</td>
<td align="right">-912.60</td>
<td align="right">-14.41</td>
</tr>
<tr class="even">
<td align="right">10009</td>
<td align="right">3406.44</td>
<td align="right">2692.19</td>
<td align="right">-714.25</td>
<td align="right">-20.97</td>
</tr>
<tr class="odd">
<td align="right">10010</td>
<td align="right">3697.28</td>
<td align="right">3012.35</td>
<td align="right">-684.93</td>
<td align="right">-18.53</td>
</tr>
<tr class="even">
<td align="right">10011</td>
<td align="right">4104.07</td>
<td align="right">3441.91</td>
<td align="right">-662.16</td>
<td align="right">-16.13</td>
</tr>
<tr class="odd">
<td align="right">10012</td>
<td align="right">3628.57</td>
<td align="right">2942.34</td>
<td align="right">-686.23</td>
<td align="right">-18.91</td>
</tr>
<tr class="even">
<td align="right">10013</td>
<td align="right">4431.87</td>
<td align="right">3797.82</td>
<td align="right">-634.05</td>
<td align="right">-14.31</td>
</tr>
<tr class="odd">
<td align="right">10014</td>
<td align="right">3768.25</td>
<td align="right">3188.49</td>
<td align="right">-579.76</td>
<td align="right">-15.39</td>
</tr>
<tr class="even">
<td align="right">10016</td>
<td align="right">3731.14</td>
<td align="right">3019.43</td>
<td align="right">-711.71</td>
<td align="right">-19.07</td>
</tr>
<tr class="odd">
<td align="right">10017</td>
<td align="right">3314.83</td>
<td align="right">2793.41</td>
<td align="right">-521.42</td>
<td align="right">-15.73</td>
</tr>
<tr class="even">
<td align="right">10018</td>
<td align="right">3893.49</td>
<td align="right">3314.23</td>
<td align="right">-579.26</td>
<td align="right">-14.88</td>
</tr>
<tr class="odd">
<td align="right">10019</td>
<td align="right">3505.28</td>
<td align="right">2970.02</td>
<td align="right">-535.26</td>
<td align="right">-15.27</td>
</tr>
<tr class="even">
<td align="right">10021</td>
<td align="right">3048.37</td>
<td align="right">2564.91</td>
<td align="right">-483.46</td>
<td align="right">-15.86</td>
</tr>
<tr class="odd">
<td align="right">10022</td>
<td align="right">3471.45</td>
<td align="right">2852.83</td>
<td align="right">-618.62</td>
<td align="right">-17.82</td>
</tr>
<tr class="even">
<td align="right">10023</td>
<td align="right">3438.90</td>
<td align="right">2895.11</td>
<td align="right">-543.79</td>
<td align="right">-15.81</td>
</tr>
</tbody>
</table>
<ul>
<li>Table2
<ul>
<li>For most zipcodes, rental prices decreased.<br />
</li>
</ul></li>
<li>largest drop in price from Jan.2020 to Jan.2021 with neighborhoods
included:</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="left">borough</th>
<th align="left">neighborhood</th>
<th align="right">Jan.2020</th>
<th align="right">Jan.2021</th>
<th align="right">drop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bronx</td>
<td align="left">Southeast Bronx</td>
<td align="right">1922.05</td>
<td align="right">1905.59</td>
<td align="right">16.46</td>
</tr>
<tr class="even">
<td align="left">Brooklyn</td>
<td align="left">Greenpoint</td>
<td align="right">3425.76</td>
<td align="right">2987.82</td>
<td align="right">437.94</td>
</tr>
<tr class="odd">
<td align="left">Manhattan</td>
<td align="left">Lower Manhattan</td>
<td align="right">6334.21</td>
<td align="right">5421.61</td>
<td align="right">912.60</td>
</tr>
<tr class="even">
<td align="left">Queens</td>
<td align="left">West Central Queens</td>
<td align="right">2509.86</td>
<td align="right">2292.88</td>
<td align="right">216.98</td>
</tr>
</tbody>
</table>
<ul>
<li>Table3
<ul>
<li><code>Lower Manhattan</code> has the largest price decrease of
<code>$912.60</code> and <code>Southeast Bronx</code> has the least
price decrease of <code>$16.46</code>.<br />
</li>
<li>Rental prices in Bronx did not drop significantly.<br />
</li>
<li>Staten Island data unavailable.</li>
</ul></li>
</ul>
<pre class="r"><code>  Plot1</code></pre>
<p><img src="within_page_files/figure-html/unnamed-chunk-1-1.png" width="1440" /></p>
<ul>
<li>Large Geographic Rental Disparities.<br />
</li>
<li>General upward rental price trend.<br />
</li>
<li>Impact of COVID-19 is clear.<br />
</li>
<li>Staten Island has lots missing data.</li>
</ul>
<pre class="r"><code>  Plot2</code></pre>
<p><img src="within_page_files/figure-html/unnamed-chunk-2-1.png" width="1152" /></p>
<ul>
<li>CA has highest house prices whereas WV has the least.<br />
</li>
<li>All states median below $1 million.</li>
<li>High Variability: CA, NY, CO; suggesting wider range of house
prices<br />
Low Variability: WV, AR, MS; suggesting more uniform house prices</li>
</ul>
<pre class="r"><code>  Plot3</code></pre>
<p><img src="within_page_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<ul>
<li><p>General positive correlation.</p></li>
<li><p>Limitations:</p>
<ul>
<li>Plentiful unavailable data for Staten Island.</li>
</ul></li>
</ul>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
